# Generated by Django 5.2.4 on 2025-08-04 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст вопроса", verbose_name="Текст вопроса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Введите текст ответа (максимум 255 символов)",
                        max_length=255,
                        verbose_name="Текст ответа",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если это правильный вариант ответа",
                        verbose_name="Правильный ответ",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Вопрос, к которому относится этот ответ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="testing.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название теста (максимум 255 символов)",
                        max_length=255,
                        verbose_name="Название теста",
                    ),
                ),
                (
                    "material",
                    models.OneToOneField(
                        help_text="Материал, к которому привязан этот тест",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="content.material",
                        verbose_name="Учебный материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                help_text="Тест, к которому относится этот вопрос",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="testing.test",
                verbose_name="Тест",
            ),
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        help_text="Процент правильных ответов", verbose_name="Результат"
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        help_text="Успешно ли пройден тест", verbose_name="Пройден"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Время завершения теста",
                        verbose_name="Дата и время прохождения",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        help_text="Тест, который проходил пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing.test",
                        verbose_name="Тест",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, проходивший тест",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка прохождения теста",
                "verbose_name_plural": "Попытки прохождения тестов",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
